#!/usr/bin/env python3
from flask import Flask, request, Response, json
from gevent.pywsgi import WSGIServer
import tensorflow as tf
from predict import predict

app = Flask(__name__)

@app.route('/invocations', methods=['POST'])
def invocations():
  if request.method == "POST":
    js = request.get_json()
    img = js['b64']
    prediction = predict(img)
    #return json.dumps(str(prediction))
    print(prediction)
    return Response(prediction, status=200, mimetype='application/json')

@app.route('/ping', methods=['GET','POST'])
def ping():
  return "Ping response"

if __name__ == '__main__':
    http_server = WSGIServer(('', 8080), app)
    http_server.serve_forever()