#!/usr/bin/env python3

from flask import Flask, request

app = Flask(__name__)

@app.route('/invocations')
def invocations():
  if request.method == "POST":
    return "Invocations response"

@app.route('/ping')
def ping():
  if request.method == "POST":
    return "Ping response"

if __name__ == '__main__':
  app.run(host='0.0.0.0', port=8080)
