#!/usr/bin/env python3
from flask import Flask, request
import tensorflow as tf

app = Flask(__name__)

@app.route('/invocations', methods=['POST'])
def invocations():
  if request.method == "POST":
    js = request.get_json()
    img = tf.io.decode_base64(js['b64'])
    return str(img)

@app.route('/ping', methods=['POST'])
def ping():
  if request.method == "POST":
    return "Ping response"

if __name__ == '__main__':
  app.run(host='0.0.0.0', port=9080)
