#!/usr/bin/env python3

import tensorflow as tf
import os
import csv

model = tf.contrib.saved_model.load_keras_model()
lables = []
with open('labels.csv') as csvfile:
    readCSV = csv.reader(csvfile, delimiter=',')
    lables = [row in readCSV]
    '''
    for row in readCSV:
        lables.append(row)
    '''
print(lables)

'''
result_batch = model.predict(image_batch)

labels_batch = label_names[np.argmax(result_batch, axis=-1)]
labels_batch
'''