#!/usr/bin/env python3

from tf.keras.preprocessing import image
import tensorflow as tf
import os
import csv

prefix = '/opt/ml/models'

model = tf.contrib.saved_model.load_keras_model(os.path.join(prefix, 'model.pb'))
lables = []
with open(os.path.join(prefix, 'labels.csv')) as csvfile:
    readCSV = csv.reader(csvfile, delimiter=',')
    lables = [row in readCSV]
    '''
    for row in readCSV:
        lables.append(row)
    '''
print(lables)

image = image.load_img('test.jpg', target_size=(224,224))
prediction = model.predict(image)


'''
result_batch = model.predict(image_batch)

labels_batch = label_names[np.argmax(result_batch, axis=-1)]
labels_batch
'''